on: push
name: Main
jobs:
  type-check-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 2.x
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Type check
      uses: CultureHQ/actions-yarn@master
      with:
        args: type-check
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: test
